# set of global variables to be accessed in the main program.
SMALL_VARIATION_ONE = [[],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       []]

SMALL_VARIATION_TWO = [[],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       []]

MED_VARIATION_ONE = [[],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     []]

MED_VARIATION_TWO = [[],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     [],
                     []]

LARGE_VARIATION_ONE = [[],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       []]

LARGE_VARIATION_TWO = [[],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       [],
                       []]
